<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="commonmodell" nsURI="http://reqexchange.ss18.sqe.tu-berlin.de/commonmodell"
    nsPrefix="commonmodell">
  <eClassifiers xsi:type="ecore:EClass" name="Identifiable" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Version" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContentObject" eSuperTypes="#//Identifiable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="propertys" upperBound="-1"
        eType="#//Property"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Specification" eSuperTypes="#//Identifiable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contentObjects" upperBound="-1"
        eType="#//ContentObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reqContainer" upperBound="-1"
        eType="#//ReqContainer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="propertySets" upperBound="-1"
        eType="#//PropertySet"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="otherSpecification" upperBound="-1"
        eType="#//Specification"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="datatypes" upperBound="-1"
        eType="#//DataType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="relationTypes" upperBound="-1"
        eType="#//RelationalType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="relations" upperBound="-1"
        eType="#//Relation" eOpposite="#//Relation/specification"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="propertys" upperBound="-1"
        eType="#//Property"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RelationalType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="propertys" upperBound="-1"
        eType="#//Property"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Relation" eSuperTypes="#//Identifiable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="propertys" upperBound="-1"
        eType="#//Property"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contentObjects" upperBound="-1"
        eType="#//ContentObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="specification" lowerBound="1"
        upperBound="2" eType="#//Specification" eOpposite="#//Specification/relations"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="relationaltype" lowerBound="1"
        eType="#//RelationalType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requirements" lowerBound="1"
        upperBound="-1" eType="#//Requirement" eOpposite="#//Requirement/relations"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReqContainer" eSuperTypes="#//Identifiable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ReqContainerChilds" upperBound="-1"
        eType="#//ReqContainer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requirements" upperBound="-1"
        eType="#//Requirement"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Requirement" eSuperTypes="#//Identifiable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="propertySets" upperBound="-1"
        eType="#//PropertySet"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="relations" upperBound="-1"
        eType="#//Relation" eOpposite="#//Relation/requirements"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PropertySet" eSuperTypes="#//Identifiable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="propertys" lowerBound="1"
        upperBound="-1" eType="#//Property"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Property">
    <eStructuralFeatures xsi:type="ecore:EReference" name="datatype" lowerBound="1"
        eType="#//DataType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="datavalue" lowerBound="1"
        eType="#//DataValue"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataValue">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1" eType="#//DataType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataType"/>
  <eClassifiers xsi:type="ecore:EClass" name="Project" eSuperTypes="#//Identifiable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="specifications" lowerBound="1"
        upperBound="-1" eType="#//Specification"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="password" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="address" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
